sudo: required
dist: trusty

cache:
  directories:
  - /home/travis/sw

language: java
jdk:
  - oraclejdk8

before_install:
  - if [[ ! -d /home/travis/sw ]];then mkdir -p /home/travis/sw ;fi
  - ls -lrth /home/travis/sw
  - export PATH=/home/travis/sw/bin:${PATH}
  - export LD_LIBRARY_PATH=/home/travis/sw/lib:${LD_LIBRARY_PATH}
  - export PKG_CONFIG_PATH=/home/travis/sw/lib/pkgconfig:${PKG_CONFIG_PATH}
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends yasm nasm 
  - sudo apt-get install -y --no-install-recommends git mercurial wget bzip2 libbz2-dev make curl cpuid pkg-config software-properties-common binutils cpp cpp-4.8 g++ g++-4.8 gcc gcc-4.8 libasan0 libatomic1 libcloog-isl4 libgcc-4.8-dev libgmp10 libgomp1 libisl10 libitm1 libmpc3 libmpfr4 libquadmath0 libstdc++-4.8-dev libtimedate-perl libtsan0 patch libtiff-dev zlib1g-dev libc6-dev
        
  #############################################################################
  # LZ4                                                                       #
  #############################################################################
  - travis_retry wget --no-check-certificate https://github.com/lz4/lz4/archive/v1.7.5.tar.gz
  - tar xf v1.7.5.tar.gz
  - pwd
  - cd lz4-1.7.5
  - if [[ ! -e /home/travis/sw/lib/liblz4.so ]]; then
      pwd &&
      sudo PREFIX=/home/travis/sw SHELL="/bin/bash -x" make install  &&
      echo "lz4 installed in /home/travis/sw" &&
      find /home/travis/sw/lib/ -name "liblz4*so";
    else
      echo "lz4 found in /home/travis/sw";
    fi
  - cd ../.. && sudo rm -rf lz4-1.7.5
  - nm /home/travis/sw/lib/liblz4.so

  #############################################################################
  # FFMPEG                                                                    #
  #############################################################################
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y libx264-dev x264  libx265-dev x265 libtiff5-dev 
  - if [[ -e /home/travis/sw/lib/libavcodec.so ]]; then
      echo "ffmpeg found in /home/travis/sw" && find /home/travis/sw/lib/ -name "libav*so";
    else
      git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg_repo && cd ffmpeg_repo && git checkout n3.0.2 &&
      ./configure --prefix=/home/travis/sw --enable-libx265 --enable-libx264 --enable-gpl --enable-shared --disable-indevs --disable-outdevs &&
      make -j2 &&
      sudo make install &&
      echo "ffmpeg installed in /home/travis/sw" && cd .. && sudo rm -rf ffmpeg_repo;
    fi
  - if [[ -e `which ffmpeg` ]]; then
        which ffmpeg && 
        find /home/travis/sw/lib /usr/lib* -name "*265*so" &&
        ldd `which ffmpeg` &&
        `which ffmpeg` -version;
    fi

  
  #############################################################################
  # HDF5                                                                       #
  #############################################################################
  - travis_retry wget --no-check-certificate https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.16/src/hdf5-1.8.16.tar.bz2
  - tar xf hdf5-1.8.16.tar.bz2
  - cd hdf5-1.8.16/
  - if [[ ! -e /home/travis/sw/lib/libhdf5_hl.so || ! -e /home/travis/sw/lib/libhdf5_hl_cpp.so ]]; then
      ./configure --enable-cxx --enable-hl --prefix=/home/travis/sw &&
      make -j2 &&
      sudo make install &&
      echo "hdf5 installed in /home/travis/sw" &&
      find /home/travis/sw/lib/ -name "libhdf*so";
    else
      echo "hdf5 found in /home/travis/sw" && find /home/travis/sw/lib/ -name "libhdf*so";
    fi
  - cd .. && sudo rm -rf hdf5-1.8.16/
  - h5ls --version

  #############################################################################
  # CMAKE                                                                     #
  #############################################################################
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.9/cmake-3.9.0.tar.gz &&
      tar xf cmake-3.9.0.tar.gz &&
      cd cmake-3.9.0 &&
      ./configure --prefix=/home/travis/sw/ && make -j2 && sudo make install &&
      cd ..;
  - cmake --version
  
  #############################################################################
  # BOOST                                                                     #
  #############################################################################
  - travis_retry wget --no-check-certificate -O boost.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2/download
  - tar xf boost.tar.bz2
  - cd boost_1_*/
  - if [[ ! -e /home/travis/sw/lib/libboost_date_time.so ]]; then
      ./bootstrap.sh --with-toolset=gcc --with-libraries=date_time,system,filesystem,test,thread,program_options,regex,serialization --prefix=/home/travis/sw &&
      ./b2 -j2 &&
      sudo ./b2 install &&
      echo "boost installed in /home/travis/sw" &&
      find /home/travis/sw/lib/ -name "libboost_*so";
    else
      echo "boost found in /home/travis/sw" && find /home/travis/sw/lib/ -name "libboost_*so";
    fi
  - cd .. && sudo rm -rf boost_1_*/
  

  #############################################################################
  # GRADLE                                                                     #
  #############################################################################
  - sudo add-apt-repository -y ppa:cwchien/gradle
  - sudo apt-get -qq update
  - sudo apt-get install gradle-3.0
  - gradle --version

  #############################################################################
  # GENERAL CHECKS                                                            #
  #############################################################################
  - ls -lrth /home/travis/sw/include/lz4.h /home/travis/sw/lib/liblz4.so
  - ls -lrth /home/travis/sw/include/boost /home/travis/sw/lib/libboost*.so
  - ls -lrth /home/travis/sw/include/hdf* /home/travis/sw/lib/libhdf*.so
  - ls -lrth /home/travis/sw/include/libav* /home/travis/sw/lib/libav*.so
  - nm /home/travis/sw/lib/liblz4.so
  - env
  - hostname
  - cpuid
  
script:
  - pwd
  - ls ${TRAVIS_BUILD_DIR}
  - if [[ -d ./sqeazy ]]; then
       cd sqeazy;
    fi
  - if [[ -d ./sqeazy ]]; then
      cd sqeazy;
    fi
  - if [[ -e ./let_me_build_that_for_you.sh ]]; then
       export LD_LIBRARY_PATH=/home/travis/sw/lib:$LD_LIBRARY_PATH &&
       export PATH=/home/travis/sw/bin:$PATH &&
       export PKG_CONFIG_PATH=/home/travis/sw/lib/pkgconfig:${PKG_CONFIG_PATH} &&
       gradle clean test && ldd build/cpp/src/libsqeazy.so && exit $?;
    fi

    
